const TONES = {
  "gong": {
    "tone": "宫",
    "mode": "宫音",
    "element": "土",
    "theme": "厚土礼乐",
    "color": "#c78d45",
    "dark": "#2a1b12",
    "light": "#f2c46e",
    "accent": "#8c4a2e"
  },
  "shang": {
    "tone": "商",
    "mode": "商音",
    "element": "金",
    "theme": "金石清声",
    "color": "#c9d2d8",
    "dark": "#111a20",
    "light": "#f0f4f5",
    "accent": "#8a9d9e"
  },
  "jiao": {
    "tone": "角",
    "mode": "角音",
    "element": "木",
    "theme": "春竹生风",
    "color": "#7fb391",
    "dark": "#10241b",
    "light": "#cde6d6",
    "accent": "#3c755e"
  },
  "zhi": {
    "tone": "徵",
    "mode": "徵音",
    "element": "火",
    "theme": "丝弦流火",
    "color": "#c9493d",
    "dark": "#2a0d0d",
    "light": "#ffb078",
    "accent": "#8f1f1c"
  },
  "yu": {
    "tone": "羽",
    "mode": "羽音",
    "element": "水",
    "theme": "水月空灵",
    "color": "#6e9dd4",
    "dark": "#071221",
    "light": "#c7e3ff",
    "accent": "#1d568a"
  }
};
const RARITIES = {
  "N": {
    "name": "凡音",
    "prob": 60,
    "color": "#75847c",
    "cost": 0
  },
  "R": {
    "name": "清音",
    "prob": 25,
    "color": "#58a184",
    "cost": 0
  },
  "SR": {
    "name": "灵韵",
    "prob": 12,
    "color": "#9aaee8",
    "cost": 0
  },
  "SSR": {
    "name": "天籁",
    "prob": 3,
    "color": "#e0b74f",
    "cost": 0
  }
};
const CARDS = [
  {
    "id": "gong_xun",
    "tone": "gong",
    "name": "宫调 · 埙",
    "instrument": "埙",
    "rarity": "SSR",
    "rarityName": "天籁",
    "pieceIndex": 1,
    "role": "远古大地乐神",
    "description": "陶土低鸣，像从大地深处传来的古老回声。",
    "image": "assets/cards/gong_xun.png",
    "toneName": "宫音",
    "element": "土"
  },
  {
    "id": "gong_dagu",
    "tone": "gong",
    "name": "宫调 · 大鼓",
    "instrument": "大鼓",
    "rarity": "SR",
    "rarityName": "灵韵",
    "pieceIndex": 2,
    "role": "雪发巾帼女帅",
    "description": "鼓声厚重如山，唤醒长夏厚土的力量。",
    "image": "assets/cards/gong_dagu.png",
    "toneName": "宫音",
    "element": "土"
  },
  {
    "id": "gong_jiangu",
    "tone": "gong",
    "name": "宫调 · 建鼓",
    "instrument": "建鼓",
    "rarity": "SR",
    "rarityName": "灵韵",
    "pieceIndex": 3,
    "role": "庙堂楹柱鼓灵",
    "description": "立鼓如柱，连接庙堂礼制与市井风声。",
    "image": "assets/cards/gong_jiangu.png",
    "toneName": "宫音",
    "element": "土"
  },
  {
    "id": "gong_fou",
    "tone": "gong",
    "name": "宫调 · 缶",
    "instrument": "缶",
    "rarity": "R",
    "rarityName": "清音",
    "pieceIndex": 4,
    "role": "秦地猛士",
    "description": "击缶声短促有力，带着古朴的陶土质感。",
    "image": "assets/cards/gong_fou.png",
    "toneName": "宫音",
    "element": "土"
  },
  {
    "id": "gong_paigu",
    "tone": "gong",
    "name": "宫调 · 排鼓",
    "instrument": "排鼓",
    "rarity": "R",
    "rarityName": "清音",
    "pieceIndex": 5,
    "role": "女谋士",
    "description": "多鼓排布，节奏层层递进，如战阵推演。",
    "image": "assets/cards/gong_paigu.png",
    "toneName": "宫音",
    "element": "土"
  },
  {
    "id": "gong_yu",
    "tone": "gong",
    "name": "宫调 · 敔",
    "instrument": "敔",
    "rarity": "N",
    "rarityName": "凡音",
    "pieceIndex": 6,
    "role": "止乐伏虎少女",
    "description": "敔主止乐，像一声收束万象的木石回响。",
    "image": "assets/cards/gong_yu.png",
    "toneName": "宫音",
    "element": "土"
  },
  {
    "id": "gong_paiban",
    "tone": "gong",
    "name": "宫调 · 拍板",
    "instrument": "拍板",
    "rarity": "N",
    "rarityName": "凡音",
    "pieceIndex": 7,
    "role": "教坊女指挥",
    "description": "檀板一合，舞台与节拍同时归位。",
    "image": "assets/cards/gong_paiban.png",
    "toneName": "宫音",
    "element": "土"
  },
  {
    "id": "gong_muyu",
    "tone": "gong",
    "name": "宫调 · 木鱼",
    "instrument": "木鱼",
    "rarity": "N",
    "rarityName": "凡音",
    "pieceIndex": 8,
    "role": "清修小沙弥",
    "description": "木音空灵，敲开尘世与静心之间的门。",
    "image": "assets/cards/gong_muyu.png",
    "toneName": "宫音",
    "element": "土"
  },
  {
    "id": "shang_bianzhong",
    "tone": "shang",
    "name": "商调 · 编钟",
    "instrument": "编钟",
    "rarity": "SSR",
    "rarityName": "天籁",
    "pieceIndex": 1,
    "role": "西周礼乐天尊",
    "description": "青铜钟声肃穆清亮，承载礼乐之重。",
    "image": "assets/cards/shang_bianzhong.png",
    "toneName": "商音",
    "element": "金"
  },
  {
    "id": "shang_bianqing",
    "tone": "shang",
    "name": "商调 · 编磬",
    "instrument": "编磬",
    "rarity": "SR",
    "rarityName": "灵韵",
    "pieceIndex": 2,
    "role": "昆仑玉女",
    "description": "玉石之声清冷如霜，回响在金石之间。",
    "image": "assets/cards/shang_bianqing.png",
    "toneName": "商音",
    "element": "金"
  },
  {
    "id": "shang_yunluo",
    "tone": "shang",
    "name": "商调 · 云锣",
    "instrument": "云锣",
    "rarity": "SR",
    "rarityName": "灵韵",
    "pieceIndex": 3,
    "role": "九天飞天乐舞",
    "description": "小锣如星，层层相映，奏出云上清声。",
    "image": "assets/cards/shang_yunluo.png",
    "toneName": "商音",
    "element": "金"
  },
  {
    "id": "shang_daluo",
    "tone": "shang",
    "name": "商调 · 大锣",
    "instrument": "大锣",
    "rarity": "R",
    "rarityName": "清音",
    "pieceIndex": 4,
    "role": "戏剧武生",
    "description": "锣声一响，场面骤开，清醒而有穿透力。",
    "image": "assets/cards/shang_daluo.png",
    "toneName": "商音",
    "element": "金"
  },
  {
    "id": "shang_naobo",
    "tone": "shang",
    "name": "商调 · 铙钹",
    "instrument": "铙钹",
    "rarity": "R",
    "rarityName": "清音",
    "pieceIndex": 5,
    "role": "社火秧歌少女",
    "description": "铜片相击，热闹中带着金石锐响。",
    "image": "assets/cards/shang_naobo.png",
    "toneName": "商音",
    "element": "金"
  },
  {
    "id": "shang_zheng",
    "tone": "shang",
    "name": "商调 · 钲",
    "instrument": "钲",
    "rarity": "N",
    "rarityName": "凡音",
    "pieceIndex": 6,
    "role": "军乐将领",
    "description": "钲声肃整，像战阵中传令的冷光。",
    "image": "assets/cards/shang_zheng.png",
    "toneName": "商音",
    "element": "金"
  },
  {
    "id": "shang_xiaoluo",
    "tone": "shang",
    "name": "商调 · 小锣",
    "instrument": "小锣",
    "rarity": "N",
    "rarityName": "凡音",
    "pieceIndex": 7,
    "role": "机敏少年",
    "description": "一声小锣，轻巧地点亮戏台节奏。",
    "image": "assets/cards/shang_xiaoluo.png",
    "toneName": "商音",
    "element": "金"
  },
  {
    "id": "shang_fangxiang",
    "tone": "shang",
    "name": "商调 · 方响",
    "instrument": "方响",
    "rarity": "N",
    "rarityName": "凡音",
    "pieceIndex": 8,
    "role": "清音匠灵",
    "description": "方响排列如阶，清脆而规整。",
    "image": "assets/cards/shang_fangxiang.png",
    "toneName": "商音",
    "element": "金"
  },
  {
    "id": "jiao_dizi",
    "tone": "jiao",
    "name": "角调 · 笛子双生",
    "instrument": "梆笛 / 曲笛",
    "rarity": "SSR",
    "rarityName": "天籁",
    "pieceIndex": 1,
    "role": "双生笛灵",
    "description": "两道笛声交错，春风从竹林深处醒来。",
    "image": "assets/cards/jiao_dizi.png",
    "toneName": "角音",
    "element": "木"
  },
  {
    "id": "jiao_dongxiao",
    "tone": "jiao",
    "name": "角调 · 洞箫",
    "instrument": "洞箫",
    "rarity": "SR",
    "rarityName": "灵韵",
    "pieceIndex": 2,
    "role": "修竹神女",
    "description": "洞箫低回清远，像雨后竹影中的一缕风。",
    "image": "assets/cards/jiao_dongxiao.png",
    "toneName": "角音",
    "element": "木"
  },
  {
    "id": "jiao_chi",
    "tone": "jiao",
    "name": "角调 · 篪",
    "instrument": "篪",
    "rarity": "SR",
    "rarityName": "灵韵",
    "pieceIndex": 3,
    "role": "雅乐小守乐官",
    "description": "古雅横吹，带着周礼旧梦与春意青光。",
    "image": "assets/cards/jiao_chi.png",
    "toneName": "角音",
    "element": "木"
  },
  {
    "id": "jiao_paixiao",
    "tone": "jiao",
    "name": "角调 · 排箫",
    "instrument": "排箫",
    "rarity": "R",
    "rarityName": "清音",
    "pieceIndex": 4,
    "role": "纯真仙童",
    "description": "竹管高低相依，吹出山谷里的层层回声。",
    "image": "assets/cards/jiao_paixiao.png",
    "toneName": "角音",
    "element": "木"
  },
  {
    "id": "jiao_bawu",
    "tone": "jiao",
    "name": "角调 · 巴乌",
    "instrument": "巴乌",
    "rarity": "R",
    "rarityName": "清音",
    "pieceIndex": 5,
    "role": "西南花影少女",
    "description": "巴乌声柔和低回，像林间花瓣落在水面。",
    "image": "assets/cards/jiao_bawu.png",
    "toneName": "角音",
    "element": "木"
  },
  {
    "id": "jiao_guanzi",
    "tone": "jiao",
    "name": "角调 · 管子",
    "instrument": "管子",
    "rarity": "N",
    "rarityName": "凡音",
    "pieceIndex": 6,
    "role": "西北乐官",
    "description": "管声有骨，风沙与春草在一线之间相撞。",
    "image": "assets/cards/jiao_guanzi.png",
    "toneName": "角音",
    "element": "木"
  },
  {
    "id": "jiao_chiba",
    "tone": "jiao",
    "name": "角调 · 尺八",
    "instrument": "尺八",
    "rarity": "N",
    "rarityName": "凡音",
    "pieceIndex": 7,
    "role": "山林行者",
    "description": "一尺竹管吹出山气，清寂而有远意。",
    "image": "assets/cards/jiao_chiba.png",
    "toneName": "角音",
    "element": "木"
  },
  {
    "id": "jiao_miaodi",
    "tone": "jiao",
    "name": "角调 · 苗笛",
    "instrument": "苗笛",
    "rarity": "N",
    "rarityName": "凡音",
    "pieceIndex": 8,
    "role": "苗岭少女",
    "description": "苗笛轻快明亮，带着山野灵风的自在。",
    "image": "assets/cards/jiao_miaodi.png",
    "toneName": "角音",
    "element": "木"
  },
  {
    "id": "zhi_guqin",
    "tone": "zhi",
    "name": "徵调 · 古琴",
    "instrument": "古琴",
    "rarity": "SSR",
    "rarityName": "天籁",
    "pieceIndex": 1,
    "role": "古琴帝师",
    "description": "七弦如星，玄音中流动着火光与文心。",
    "image": "assets/cards/zhi_guqin.png",
    "toneName": "徵音",
    "element": "火"
  },
  {
    "id": "zhi_pipa",
    "tone": "zhi",
    "name": "徵调 · 琵琶",
    "instrument": "琵琶",
    "rarity": "SR",
    "rarityName": "灵韵",
    "pieceIndex": 2,
    "role": "琵琶女侠",
    "description": "四弦翻飞，战意与飞天薄纱一同燃起。",
    "image": "assets/cards/zhi_pipa.png",
    "toneName": "徵音",
    "element": "火"
  },
  {
    "id": "zhi_konghou",
    "tone": "zhi",
    "name": "徵调 · 箜篌",
    "instrument": "箜篌",
    "rarity": "SR",
    "rarityName": "灵韵",
    "pieceIndex": 3,
    "role": "盛唐飞天姬",
    "description": "箜篌如虹，拨动长安旧梦里的流光。",
    "image": "assets/cards/zhi_konghou.png",
    "toneName": "徵音",
    "element": "火"
  },
  {
    "id": "zhi_guzheng",
    "tone": "zhi",
    "name": "徵调 · 古筝",
    "instrument": "古筝",
    "rarity": "R",
    "rarityName": "清音",
    "pieceIndex": 4,
    "role": "丝乐姬",
    "description": "筝弦如潮，火色音浪割开夜幕。",
    "image": "assets/cards/zhi_guzheng.png",
    "toneName": "徵音",
    "element": "火"
  },
  {
    "id": "zhi_se",
    "tone": "zhi",
    "name": "徵调 · 瑟",
    "instrument": "瑟",
    "rarity": "R",
    "rarityName": "清音",
    "pieceIndex": 5,
    "role": "乐之女王",
    "description": "瑟音庄重华丽，像礼乐中的赤金长河。",
    "image": "assets/cards/zhi_se.png",
    "toneName": "徵音",
    "element": "火"
  },
  {
    "id": "zhi_ruan",
    "tone": "zhi",
    "name": "徵调 · 阮",
    "instrument": "阮",
    "rarity": "N",
    "rarityName": "凡音",
    "pieceIndex": 6,
    "role": "魏晋名士",
    "description": "圆月琴身微亮，酒意与竹林风相互回旋。",
    "image": "assets/cards/zhi_ruan.png",
    "toneName": "徵音",
    "element": "火"
  },
  {
    "id": "zhi_erhu",
    "tone": "zhi",
    "name": "徵调 · 二胡",
    "instrument": "二胡",
    "rarity": "N",
    "rarityName": "凡音",
    "pieceIndex": 7,
    "role": "红尘弦灵",
    "description": "两弦一弓，拉出万家灯火与人间悲喜。",
    "image": "assets/cards/zhi_erhu.png",
    "toneName": "徵音",
    "element": "火"
  },
  {
    "id": "zhi_matouqin",
    "tone": "zhi",
    "name": "徵调 · 马头琴",
    "instrument": "马头琴",
    "rarity": "N",
    "rarityName": "凡音",
    "pieceIndex": 8,
    "role": "草原乐神",
    "description": "弓弦如风，带来草原星夜的辽阔回声。",
    "image": "assets/cards/zhi_matouqin.png",
    "toneName": "徵音",
    "element": "火"
  },
  {
    "id": "yu_suona",
    "tone": "yu",
    "name": "羽调 · 唢呐",
    "instrument": "唢呐",
    "rarity": "SSR",
    "rarityName": "天籁",
    "pieceIndex": 1,
    "role": "流火女王",
    "description": "唢呐一响，生死红尘都被声浪点燃。",
    "image": "assets/cards/yu_suona.png",
    "toneName": "羽音",
    "element": "水"
  },
  {
    "id": "yu_sheng",
    "tone": "yu",
    "name": "羽调 · 笙",
    "instrument": "笙",
    "rarity": "SR",
    "rarityName": "灵韵",
    "pieceIndex": 2,
    "role": "凤翼笙神",
    "description": "笙管如凤翼，气息在水月之间缓缓升起。",
    "image": "assets/cards/yu_sheng.png",
    "toneName": "羽音",
    "element": "水"
  },
  {
    "id": "yu_yu",
    "tone": "yu",
    "name": "羽调 · 竽",
    "instrument": "竽",
    "rarity": "SR",
    "rarityName": "灵韵",
    "pieceIndex": 3,
    "role": "朝堂大乐官",
    "description": "竽声深远，像古老殿宇里的群音回潮。",
    "image": "assets/cards/yu_yu.png",
    "toneName": "羽音",
    "element": "水"
  },
  {
    "id": "yu_hulusi",
    "tone": "yu",
    "name": "羽调 · 葫芦丝",
    "instrument": "葫芦丝",
    "rarity": "R",
    "rarityName": "清音",
    "pieceIndex": 4,
    "role": "白衣柔音少女",
    "description": "葫芦丝温柔婉转，像夜水中的一朵白莲。",
    "image": "assets/cards/yu_hulusi.png",
    "toneName": "羽音",
    "element": "水"
  },
  {
    "id": "yu_lusheng",
    "tone": "yu",
    "name": "羽调 · 芦笙",
    "instrument": "芦笙",
    "rarity": "R",
    "rarityName": "清音",
    "pieceIndex": 5,
    "role": "苗族少年",
    "description": "芦笙起舞，银铃与水雾在夜色里相和。",
    "image": "assets/cards/yu_lusheng.png",
    "toneName": "羽音",
    "element": "水"
  },
  {
    "id": "yu_fengsheng",
    "tone": "yu",
    "name": "羽调 · 凤笙",
    "instrument": "凤笙",
    "rarity": "N",
    "rarityName": "凡音",
    "pieceIndex": 6,
    "role": "寒羽童子",
    "description": "凤笙轻鸣，冰蓝气息化成细小羽光。",
    "image": "assets/cards/yu_fengsheng.png",
    "toneName": "羽音",
    "element": "水"
  },
  {
    "id": "yu_paisheng",
    "tone": "yu",
    "name": "羽调 · 排笙",
    "instrument": "排笙",
    "rarity": "N",
    "rarityName": "凡音",
    "pieceIndex": 7,
    "role": "水桥乐灵",
    "description": "排笙层叠，像桥下水声一层层漫开。",
    "image": "assets/cards/yu_paisheng.png",
    "toneName": "羽音",
    "element": "水"
  },
  {
    "id": "yu_mangtong",
    "tone": "yu",
    "name": "羽调 · 芒筒",
    "instrument": "芒筒",
    "rarity": "N",
    "rarityName": "凡音",
    "pieceIndex": 8,
    "role": "山水筒音灵",
    "description": "芒筒低沉悠长，带来山谷夜雾里的回声。",
    "image": "assets/cards/yu_mangtong.png",
    "toneName": "羽音",
    "element": "水"
  }
];
